import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import UserContextProvider from "./contexts/UserContext";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={outfit.className}>
      <UserContextProvider>
        <Navbar/>

        {children}

        </UserContextProvider>
        </body>
    </html>
  );
}
