import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import DataContextProvider from "./contexts/DataContext";
import Footer from "@/components/Footer";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Cafe de Altura",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={outfit.className}>
      <DataContextProvider>
        <Navbar/>

       <main>{children}</main>


        <Footer/>
        </DataContextProvider>
        </body>
    </html>
  );
}
